name: PHP/MySQL CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Start a MySQL container for testing purposes.
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: cryptledger
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Use a modern, supported PHP version
        extensions: mysqli, pdo_mysql

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-interaction --no-progress --no-dev

    - name: Wait for MySQL to be ready
      run: |
        while ! mysqladmin ping -h127.0.0.1 --silent; do
          sleep 1
        done

    - name: Create database tables
      run: mysql -h 127.0.0.1 -u root -e "CREATE DATABASE cryptledger;"

    - name: Test database connection
      run: |
        php -r "require_once 'multi_db_connect.php'; try { pdo_connect_mysql(); echo 'Database connection successful!'; } catch (PDOException \$e) { exit(1); }"
